### ISSUE TITLE
Transcoding not working?

### ISSUE THREAD

**Issue by hannes** [AlexPresso/MediaServer-ffmpeg-patcher#2]
Hi, thanks for this project, really happy to see someone has addressed this annoying issue. 
I ran the patcher as instructed, but it seems not to be working for me. I have a fairly recent LG TV, and a video file with DTS and several non-DTS streams in it:

```
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 
    Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1 (default)
    Stream #0:2(deu): Audio: ac3, 48000 Hz, stereo, 192 kb/s
    Stream #0:3(spa): Audio: ac3, 48000 Hz, stereo, 192 kb/s
````
etc. 

After applying the patch, the TV says "This video does not support audio", and switches to the second (German) stream. It's not like I don't speak German but I enjoy TNG more in English. 

Any ideas?

**Comment by AlexPresso** [comment]
Hi, I'm glad you like the project and sorry to hear it doesn't work for you.
Have you enabled audio transcoding in the MediaServer settings ?

**Comment by hannes** [comment]
I have enabled it, yes.

**Comment by hannes** [comment]
Here is the log of the installation and a screen shot of my media server settings
```
sh-4.4# curl https://raw.githubusercontent.com/AlexPresso/mediaserver-ffmpeg-patcher/main/patcher.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3153  100  3153    0     0  11130      0 --:--:-- --:--:-- --:--:-- 11180
[2022-11-06 07:25:49] [INFO] You're running DSM 7.1.1
[2022-11-06 07:25:49] [INFO] ====== Patching procedure (branch: main) ======
[2022-11-06 07:25:49] [INFO] Saving current ffmpeg as ffmpeg.orig
[2022-11-06 07:25:49] [INFO] Downloading and installing ffmpeg's wrapper...
[2022-11-06 07:26:05] [INFO] Saving current libsynovte.so as libsynovte.so.orig
[2022-11-06 07:26:05] [INFO] Enabling eac3, dts and truehd
[2022-11-06 07:26:05] [INFO] Restarting MediaServer...
restart package [MediaServer] successfully

[2022-11-06 07:26:08] [INFO] Done patching, you can now enjoy your movies ;) (please add a star to the repo if it worked for you)
```

<img width="688" alt="Screenshot 2022-11-06 at 07 27 03" src="https://user-images.githubusercontent.com/227792/200157458-1fff798f-0ea1-4c49-abfe-eeb4b7c40923.png">
